name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20.x'
        - name: Install dependencies
          run: npm install
        - name: Running Tests        
          run: npm test
    
        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v3
          with:
            name: node-app
            path: .
  deploy:
    needs: build
      
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      # - name: Copy folder content recursively to remote
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     local: test
      #     remote: scp/directory
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.PASSWORD }}
